version: '3'


services:
  frontend: 
    environment: 
      - "backendApiURL='http://localhost:8080/heronames'"
    build:  ./angular-tour-of-heroes-master
    ports:
     - "8000:80"

  backend:
    build: ./rest
    ports:
     - "8080:8080"
